<?php
	function news_tape_schema() {
	  $schema['news_tape'] = array(
		'fields' => array(
		  'id' => array('type' => 'serial', 'not null' => TRUE),
		  'title' => array('type' => 'varchar', 'length' => 255, 'not null' => TRUE),
		  'body' => array('type' => 'varchar', 'length' => 1255, 'not null' => TRUE),
		  'date' => array('type' => 'varchar', 'length' => 30, 'not null' => TRUE)
		),
	   'primary key' => array('id'),
	  );
	  
	  return $schema;
	}