//v128 (c) 2008-2016 33Across Inc. All Rights Reserved

Tynt=window.Tynt||[];
"undefined"==typeof Tynt.TIL&&"undefined"==typeof Tynt.TCL&&function(){var e=window,g=document,n={distro:"TC-"+(new Date).getTime()};Tynt.TCL=function(){function H(a){var b=H.options;a=b.parser[b.strictMode?"strict":"loose"].exec(a);for(var c={},d=14;d--;)c[b.key[d]]=a[d]||"";c[b.q.name]={};c[b.key[12]].replace(b.q.parser,function(a,d,f){d&&(c[b.q.name][d]=f)});return c}if(document.body){Date.now||(Date.now=function(){return(new Date).getTime()});var h={_maxRef:800,_idMacro:"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",init:function(){this._icUrl=
n.protocol+(Tynt.e||"")+"ic.tynt.com";this._debUrl=n.protocol+(Tynt.e||"")+"de.tynt.com/deb/v2";this._sicUrl=n.protocol+(Tynt.e||"")+"cdn-sic.33across.com/1/javascripts/sic.js";this._apUrl=n.protocol+(Tynt.e||"")+"cdn-ap.33across.com/javascripts/ap.js"},newEle:function(a,b,c,d){d=d||window;a=d.document.createElement(a);b&&this.extend(a,b);c&&this.extend(a.style,c);return a},injectScript:function(a,b,c){b=b||window;a=this.newEle("script",{async:"async",type:"text/javascript",src:a},null,b);this.insertEle(a,
c||b.document.getElementsByTagName("script")[0])},injectSicScript:function(a){this.injectScript(this._sicUrl,window,a)},injectApolloScript:function(){this.injectScript(this._apUrl)},injectSicIframe:function(a,b,c){var d={width:a.width+"px",height:a.height+"px",border:"0 none",margin:"0"};c&&this.extend(d,c);c=this.newEle("iframe",{src:"about:blank",frameBorder:"0",frameSpacing:"0",scrolling:"no"},d);this.insertEle(c,b);a.iframeId=this.eleId(c);a.sicWindow=c.contentWindow;a=c.contentWindow.document;
a.open();a.write('<!DOCTYPE html><html><head><style type="text/css">*{margin:0;padding:0;}</style></head><body><script type="text/javascript">window.Tynt = window.parent.Tynt;\x3c/script><script type="text/javascript" src="'+this._sicUrl+'">\x3c/script></body></html>');a.close()},insertEle:function(a,b){b?"script"==b.tagName.toLowerCase()?b.parentNode.insertBefore(a,b):b.appendChild(a):document.body.appendChild(a)},eleId:function(a){var b=a.id;b||(b="x33x"+Date.now(),a.id=b);return b},injectPixel:function(a,
b,c){var d;try{d=g.createElement("img")}catch(e){d=document.createElement("img")}d&&(b&&(d.onload=b),c&&(d.onerror=c),d.src=a)},docUrl:function(){var a,b=null,c;c=g.getElementsByTagName("link");for(a=0;a<c.length;++a)c[a].getAttribute("href")&&c[a].getAttribute("rel")&&0<=c[a].getAttribute("rel").indexOf("canonical")&&(b=c[a].href);b||(b=this.getMeta("property","og:url","name","original-source"));return b?(0!=b.indexOf("http")&&(a=n.protocol+e.location.host+e.location.pathname,(c=g.getElementsByTagName("base")[0])&&
(c=c.getAttribute("href"))&&(a=c),"/"==b.charAt(0)?(c=a.indexOf("/",9),-1<c&&(a=a.slice(0,c))):(c=a.lastIndexOf("/"),a=9<c?a.slice(0,c+1):a+"/"),b=a+b),b):""},getMeta:function(a,b,c,d){var e,k=null,f=null,B=g.getElementsByTagName("meta");for(e=0;e<B.length;++e)k||B[e].getAttribute(a)!==b?c&&!f&&B[e].getAttribute(c)===d&&(f=B[e].getAttribute("content")||null):k=B[e].getAttribute("content")||null;return k||f},extend:function(a,b){var c,d;for(c=1;c<arguments.length;++c)for(d in arguments[c])arguments[c].hasOwnProperty(d)&&
(a[d]=arguments[c][d]);return a},isArray:function(a){return"undefined"!=typeof a&&"[object Array]"===Object.prototype.toString.call(a)},inArray:function(a,b){return 0<=this.indexOf(a,b)},toArray:function(a,b){return Array.prototype.slice.call(a,b||0)},indexOf:function(a,b){if(a.indexOf)return a.indexOf(b);for(var c=0;c<a.length;++c)if(a[c]===b)return c;return-1},unique:function(a){var b,c={},d=[];for(b=0;b<a.length;++b)c[a[b]]||(c[a[b]]=!0,d.push(a[b]));return d},iframeType:function(){var a=this.iframeEle(),
b=0;if(a)a.id&&0<=a.id.search(/google_ads?_i?frame/)?(b=6,h.log(1,"In same-origin iframe from DFP")):(b=5,h.log(1,"In same-origin iframe"));else try{window!=window.top?"undefined"!=typeof window.$sf?(b=4,h.log(1,"In SafeFrame")):(b=3,h.log(1,"In cross-origin iframe")):h.log(1,"In top window")}catch(c){b=3,h.log(1,"DEBUG: exception 2")}return b},iframeEle:function(a){var b=null;a=a||window;try{b=a.frameElement}catch(c){}return b},iframeTop:function(){var a=window,b=null;try{for(;a!=window.top;)b=a,
a=a.parent}catch(c){return null}return b?this.iframeEle(b):null},getTopWin:function(){var a=window;try{for(;a.parent!==a&&a.parent.document;)a=a.parent}catch(b){}return a},jsonDecode:function(a){if("function"!==typeof Array.prototype.toJSON)return JSON.stringify(a);var b=Array.prototype.toJSON;delete Array.prototype.toJSON;a=JSON.stringify(a);Array.prototype.toJSON=b;return a},getCookie:function(a,b){for(var c=b+"=",d=a.split(";"),e=0;e<d.length;e++){for(var k=d[e];" "==k.charAt(0);)k=k.substring(1,
k.length);if(0===k.indexOf(c))return k.substring(c.length,k.length)}return null},trim:function(a){return a.replace(/^\s+|\s+$/g,"")},trunc:function(a,b){var c,d;if(!a||a.length<=b)return a;c=a.substring(0,b);for(d=1;3>=d;++d)if("%"==c.charAt(c.length-d))return c.substring(0,c.length-d);return c},tyntIds:function(){return this.unique(Tynt).join("~")},log:function(){var a;"undefined"==typeof Tynt.debug&&0<e.location.search.indexOf("__tcdebugmode=1")&&e.console&&e.console.log&&(Tynt.debug=1);1===Tynt.debug&&
(a=this.toArray(arguments),1===a[0]&&(a[0]=n.distro),a.unshift("[TC]"),e.console.log.apply(e.console,a))},callIc:function(){var a,b,c,d,A,k,f;if(!e._33Across.state.icDone){e._33Across.state.icDone=1;b=this.getCookie(g.cookie,"tracertraffic");a=e.location.hash;a=/tynt=/.test(a)?a.match(/tynt=?([^?&$#]*)/)[1]:!1;d=c=this._icUrl+"/b/p?id="+this.tyntIds()+(b?"&et="+b:"")+(a?"&a="+a:"")+("string"==typeof Tynt.b?"&b="+Tynt.b:"")+"&lm="+n.type+"&ts="+Date.now();(a=this.getMeta("property","og:image:url",
"property","og:image"))&&(d+="&img="+encodeURIComponent(this.trunc(a,255)));A=d;(a=this.getMeta("property","og:title"))&&a!=g.title&&(A+="&ct="+encodeURIComponent(this.trunc(a,127)));k=A;g.referrer&&(a=this.trunc(g.referrer,this._maxRef),k+="&r="+encodeURIComponent(a));f=k;if(a=g.title||e.location.hostname)a=this.trim(this.trunc(a,200)),f+="&t="+encodeURIComponent(a);b=f;if(a=this.docUrl())a=this.trunc(a,500),b+="&cu="+encodeURIComponent(a);h.callIc.rsp=function(){e._33Across.state.icDone=2};h.log(1,
"Calling IC");this.injectPixel(b,h.callIc.rsp,function(){h.injectPixel(f,h.callIc.rsp,function(){h.injectPixel(k,h.callIc.rsp,function(){h.injectPixel(A,h.callIc.rsp,function(){h.injectPixel(d,h.callIc.rsp,function(){h.injectPixel(c,h.callIc.rsp)})})})})})}},callDeb:function(a){if("undefined"==typeof a){if(e._33Across.state.deDone)return;a=4}e._33Across.state.deDone=!0;0==a||2==e._33Across.state.icDone?(h.log(1,"Calling DEB"+(0==a?" on IC timeout":"")),this.injectScript(this._debUrl+"?id="+this.tyntIds()+
"&r="+encodeURIComponent(this.trunc(g.referrer,this._maxRef)),e)):setTimeout(function(){h.callDeb(a-1)},50)}};n.type=h.iframeType();5<=n.type&&(e=h.getTopWin(),g=e.document);e._33Across||(e._33Across={});e._33Across.state||(e._33Across.state={icDone:0,deDone:!1,ivDone:!1});"https:"===e.location.protocol?(n.isSecure=!0,n.protocol="https://"):(n.isSecure=!1,n.protocol="http://");h.init();H.options={strictMode:!1,key:"source protocol authority userInfo user password host port relative path directory file query anchor".split(" "),
q:{name:"queryKey",parser:/(?:^|&)([^&=]*)=?([^&]*)/g},parser:{strict:/^(?:([^:\/?#]+):)?(?:\/\/((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?))?((((?:[^?#\/]*\/)*)([^?#]*))(?:\?([^#]*))?(?:#(.*))?)/,loose:/^(?:(?![^:@]+:[^:@\/]*@)([^:\/?#.]+):)?(?:\/\/)?((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/}};var l=g.body,m=g.documentElement,R=e.eval("/*@cc_on!@*/false"),I=function(a,b){for(var c="",
d=0;d<b;d++)c+=a;return c},D=I("a",50),C=(Tynt.e||"")+"ic.tynt.com",J=C+"/b/s",K;K=e.addEventListener?function(a,b,c){a.addEventListener(b,c,!1)}:function(a,b,c){a.attachEvent("on"+b,c)};var S=function(a){"complete"==g.readyState?a():K(e,"load",function(b){setTimeout(function(){"undefined"!=typeof g.readyState||R||(g.readyState="complete");a()},10)})},w=function(a,b){var c=[],d=function(a,b){var c=n.protocol+a.replace("id="+D,"id="+h.tyntIds());-1<c.indexOf(C+"/b/p?")&&"string"==typeof Tynt.b&&(c+=
"&b="+Tynt.b);var d=new Image(1,1);b&&(d.onerror=b);d.src=c};w=function(a,b){c.push([a,b])};S(function(){w=d;for(var a=0;a<c.length;a++)w(c[a][0],c[a][1]);c=null});w(a,b)},L=function(a){var b=[],c="",d;for(d in a)a.hasOwnProperty(d)&&(b.push(c,d,"=",a[d]),c="&");return b.join("")},N=function(a){for(var b=0,c=100>a.length?a.length:100,d=0;d<c;d++)b+=a.charCodeAt(d);a=Math.floor(3844*Math.random());c=Math.abs(Date.now()-12281184E5);return M(c,7)+M((b+a)%3844,2)},O=function(a){if(62>a)return"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(this);
var b=Math.floor(a/62);a-=62*b;return 62<=b?O(b)+"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(a):"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(b)+"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(a)},M=function(a,b){var c=O(a);return I("0",b-c.length)+c},T=h.trim((g.title||e.location.hostname).toString()).replace(new RegExp(e.location.hash,"g"),""),U=function(){if(-1!==g.cookie.indexOf("tracertraffic=")&&(!g.referrer||-1==
g.referrer.indexOf(e.location.host))){var a=e.location.hostname.split("."),b,c=2;do b="tracertraffic=0;path=/;domain=."+a.slice(a.length-c,a.length).join(".")+";expires=Thu, 01 Jan 1970 00:00:00 GMT",g.cookie=b,c++;while(-1==g.cookie.indexOf("tracertraffic=0")&&c<=a.length);-1==g.cookie.indexOf("tracertraffic=0")&&(g.cookie="tracertraffic=0;path=/;expires=Thu, 01 Jan 1970 00:00:00 GMT")}},u=function(){var a=[];return function(b){for(var c=a.length-1;0<=c;c--)if(a[c]==b)return!1;a.unshift(b);3<a.length&&
a.pop();return!0}},V=u(),W=u(),X=function(a){var b,c=function(a){e.removeEventListener("blur",c,!1);z(b);return!0};return function(a){b=a.target||a.srcElement;e.removeEventListener("blur",c,!1);"IMG"==b.nodeName&&"A"!=b.parentNode.nodeName&&(e.addEventListener("blur",c,!1),setTimeout(function(){g.removeEventListener("blur",c,!1)},1E4));return!0}}(),P=function(a){z(a.target||a.srcElement,!0)},v,Q=function(a){a=a.target||a.srcElement;v="IMG"==a.nodeName?a:null},G=function(a){var b=function(a){return"number"==
typeof a.pageX?{x:a.pageX-(m.scrollLeft?m.scrollLeft:l.scrollLeft),y:a.pageY-(m.scrollTop?m.scrollTop:l.scrollTop)}:{x:a.clientX,y:a.clientY}},c=function(a){a=b(a);return 0>=a.x||0>=a.y||a.x>=l.clientWidth||a.y>=l.clientHeight},d=function(a){a=b(a);return 0>=a.x||0>=a.y||a.x>=m.clientWidth||a.y>=m.clientHeight},e=function(a){return"#document"==a.target.nodeName},k=function(a){a=b(a);return 4>=a.x||4>=a.y||a.x>=m.clientWidth-4||a.y>=m.clientHeight-4},f=function(a){f=navigator.userAgent.match("MSIE")?
g.compatMode&&-1!=g.compatMode.indexOf("CSS")?d:c:navigator.userAgent.match("Firefox")?e:k;f(a)};return function(a){v&&f(a)&&(z(v),v=null);return!0}}();Tynt.ci=function(){var a;return function(b,c){a=c||a;var d=J+["?ci=",b,"&id=",D,"&g=",a,"&r=",encodeURIComponent(g.referrer),"&ts=",Date.now()].join("");w(d)}}();Tynt.st=function(){var a;return function(b,c,d,h){a=d||a;b=[J,"?",encodeURIComponent(b),"=",encodeURIComponent(c),"&id=",D,"&g=",a,"&r=",encodeURIComponent(g.referrer),"&href=",encodeURIComponent(e.location.href),
"&ts=",Date.now()];c="";if(h){c=[];d="";for(var k in h)h.hasOwnProperty(k)&&(c.push(d,encodeURIComponent(k),"=",encodeURIComponent(h[k])),d="&");c="&"+c.join("")}w(b.join("")+c)}}();Tynt.c?u=function(){}:(Tynt.c=!0,Tynt.m=Tynt.m||[],Tynt.n=Tynt.n||[],u=function(){var a=!0,b,c=function(b,c){var e;e=(e=h.trim(c))?e.split(/\s+/i).length:0;var f={id:D,wc:e,c:c,f:a?1:0,t:T};h.extend(f,b);a=!1;e=f.trace_type;delete f.trace_type;var g=f.g;delete f.g;for(var p=[],t="id wc f w h t c".split(" "),r=0;r<t.length;r++){var m=
t[r],l=f[m];l&&p.push([m,encodeURIComponent(l).replace(/\'/g,"%27")]);delete f[m]}for(var q in f)f.hasOwnProperty(q)&&(t=f[q])&&p.push([q,encodeURIComponent(t).replace(/\'/g,"%27")]);q=[];var r=2048-((n.protocol+C+"/a/t/x#?").length+(3+g.length)+5),m=p.length,x=l=0,y=0,u,v,z,E,F=0;for(q[F]={g:g,tp:null};l<m&&35>q.length;)u=p[l][0],f=p[l][1],z=u.length+2,v=r-z-x,0<v?(t=f.substring(y,y+v),E=t.slice(-2).indexOf("%"),-1<E&&(t=f.substring(y,y+v-2+E),x+=E+2),x+=t.length+z,y+=t.length,q[F][u]=t):x=r,x>=
r&&(q[++F]={g:g,p:F},x=0),y>=f.length&&(l++,y=0);q[0].tp=q.length;w(C+"/b/t/"+e+"?"+L(q[0]));for(g=1;g<q.length;g++)w(C+"/b/x/"+e+"?"+L(q[g]))};e.addEventListener?(navigator.userAgent.match(/Firefox\/2\b/)||l.addEventListener("copy",P,!1),e.addEventListener("mousedown",Q,!1),e.addEventListener("dragleave",G,!1),e.addEventListener("dragexit",G,!1),g.addEventListener("contextmenu",X,!1)):(l.attachEvent("oncopy",P),g.getElementsByTagName("html")[0].attachEvent("ondragleave",G),l.attachEvent("onmousedown",
Q));U();h.callIc();h.callDeb();return function(a,n){if(!g.getElementById("tyntSh")){var k,f,l;n&&(g.selection&&g.selection.createRange?(f=g.selection.createRange(),l=f.duplicate(),k=f.text):(f=e.getSelection(),l=0<f.rangeCount&&f.getRangeAt(0),k=f.toString()));var p=a.src;if(p&&!k&&W(p)){f={trace_type:3,g:N(p),w:a.width,h:a.height};for(l=0;l<Tynt.n.length;l++)Tynt.n[l](f,p);c(f,p)}else if(k&&h.trim(k).length&&"TEXTAREA"!=a.nodeName&&"INPUT"!=a.nodeName){p=V(k);f={trace_type:1};p&&(b=N(k));f.g=b;for(var m=
!0,r=0;r<Tynt.m.length;r++)m=m&&Tynt.m[r](f,k,l,p);p&&m&&c(f,k)}}}});if(!/tracer=test|tracer=no_tracing|disableTracer=/.test(e.location.href)&&!/disableTracer=y/.test(g.cookie))var z=u()}else setTimeout(function(){Tynt.TCL()},62)};Tynt.TCL()}();
