(function(){var l=Handlebars.template;(Handlebars.discovery=Handlebars.discovery||{}).templates=l(function(g,k,f,i,a){function b(a,e,x){var d="",c,b;d+='\n        <li class="discovery-post" id="discovery-link-';(c=f.domIdSuffix)?c=c.call(a,{hash:{},data:e}):(c=a.domIdSuffix,c=typeof c===q?c.apply(a):c);d+=n(c)+'">\n            <header class="discovery-post-header">\n                <h3 title="';(c=f.title)?c=c.call(a,{hash:{},data:e}):(c=a.title,c=typeof c===q?c.apply(a):c);d+=n(c)+'">\n                    <a ';
if((c=j.invokePartial(i.linkAttributes,"linkAttributes",a,f,i,e))||c===0)d+=c;d+=' data-role="discovery-thread-title" class="title publisher-anchor-color line-truncate" data-line-truncate="2">\n                        '+n(f.html.call(a,a.title,{hash:{},data:e}))+"\n                    </a>\n\n                    ";if((b=f["if"].call(a,(c=x.variant,c==null||c===!1?c:c.inlineMeta),{hash:{},inverse:j.noop,fn:j.program(3,h,e),data:e}))||b===0)d+=b;d+="\n\n                </h3>\n\n                ";if((b=
f.unless.call(a,(c=x.variant,c==null||c===!1?c:c.inlineMeta),{hash:{},inverse:j.noop,fn:j.program(11,w,e),data:e}))||b===0)d+=b;d+="\n\n            </header>\n\n            ";if((b=f["if"].call(a,(c=x.variant,c==null||c===!1?c:c.contentPreviews)&&a.preview,{hash:{},inverse:j.noop,fn:j.program(16,m,e),data:e}))||b===0)d+=b;d+="\n\n        </li>\n    ";return d}function h(a,e){var b="",d;b+="\n                        ";if((d=f["if"].call(a,a.posts>0,{hash:{},inverse:j.program(6,r,e),fn:j.program(4,
c,e),data:e}))||d===0)b+=d;b+="\n                        ";if((d=f["if"].call(a,a.brand,{hash:{},inverse:j.noop,fn:j.program(9,y,e),data:e}))||d===0)b+=d;b+="\n                    ";return b}function c(a,e){var c="",d;c+='\n                            <span class="inline-meta">\n                                ';if((d=j.invokePartial(i.discoveryPostCount,"discoveryPostCount",a,f,i,e))||d===0)c+=d;c+="\n                            </span>\n                        ";return c}function r(a,c){var b="",
d;b+="\n                            ";if((d=f["if"].call(a,a.createdAgo,{hash:{},inverse:j.noop,fn:j.program(7,e,c),data:c}))||d===0)b+=d;b+="\n                        ";return b}function e(a,e){var c="",d;c+='\n                                <span class="inline-meta">';(d=f.createdAgo)?d=d.call(a,{hash:{},data:e}):(d=a.createdAgo,d=typeof d===q?d.apply(a):d);c+=n(d)+"</span>\n                            ";return c}function y(a,c){var e="",d;e+='\n                            <span class="inline-meta">\n                                ';
(d=f.brand)?d=d.call(a,{hash:{},data:c}):(d=a.brand,d=typeof d===q?d.apply(a):d);e+=n(d)+"\n                            </span>\n                        ";return e}function w(a,e){var c="",d;c+='\n                    <ul class="meta">\n                        ';if((d=f["if"].call(a,a.posts>0,{hash:{},inverse:j.noop,fn:j.program(12,u,e),data:e}))||d===0)c+=d;c+="\n                        ";if((d=f["if"].call(a,a.createdAgo,{hash:{},inverse:j.noop,fn:j.program(14,p,e),data:e}))||d===0)c+=d;c+="\n                    </ul>\n                ";
return c}function u(a,c){var e="",d;e+='\n                            <li class="comments">\n                                ';if((d=j.invokePartial(i.discoveryPostCount,"discoveryPostCount",a,f,i,c))||d===0)e+=d;e+="\n                            </li>\n                        ";return e}function p(a,e){var c="",d;c+='\n                            <li class="time">';(d=f.createdAgo)?d=d.call(a,{hash:{},data:e}):(d=a.createdAgo,d=typeof d===q?d.apply(a):d);c+=n(d)+"</li>\n                        ";
return c}function m(a,c){var e="",d;e+="\n                ";if((d=j.invokePartial(i.discoveryContentPreview,"discoveryContentPreview",a,f,i,c))||d===0)e+=d;e+="\n            ";return e}function s(){return'target="_blank" rel="nofollow"'}function t(a,e){var c="";c+="\n        "+n(f.t.call(a,gettext("1 comment"),{hash:{},data:e}))+"\n    ";return c}function l(a,e){var c="";c+="\n        "+n(f.t.call(a,gettext("%(numPosts)s comments"),{hash:{numPosts:a.posts},data:e}))+"\n    ";return c}function z(a,
e,c){var d="",b;d+='\n        <section id="';(b=f.id)?b=b.call(a,{hash:{},data:e}):(b=a.id,b=typeof b===q?b.apply(a):b);d+=n(b)+'" class="';(b=f.className)?b=b.call(a,{hash:{},data:e}):(b=a.className,b=typeof b===q?b.apply(a):b);d+=n(b)+'">\n            <header class="discovery-col-header">\n\n                ';if((b=f["if"].call(a,e.index===e.length-1,{hash:{},inverse:j.noop,fn:j.program(30,A,e),data:e}))||b===0)d+=b;d+="\n\n                ";if((b=f["if"].call(a,a.type==="organic",{hash:{},inverse:j.noop,
fn:j.programWithDepth(B,e,c),data:e}))||b===0)d+=b;d+="\n                ";if((b=f["if"].call(a,a.type==="promoted",{hash:{},inverse:j.noop,fn:j.program(34,C,e),data:e}))||b===0)d+=b;d+='\n\n            </header>\n            <ul class="discovery-posts">\n            </ul>\n        </section>\n    ';return d}function A(a,e){var c="";c+='\n                    \n                    <div class="discovery-options">\n                        <span class="publisher-anchor-color"><a href="#" class="discovery-help" data-action="discovery-help">'+
n(f.t.call(a,gettext("What's this?"),{hash:{},data:e}))+"</a></span>\n                    </div>\n                ";return c}function B(a,e,c){var d="";d+="\n                    <h2>"+n(f.t.call(a,gettext("Also on %(forumName)s"),{hash:{forumName:{partial:"forumName",context:c.forum,executePartial:!0}},data:e}))+"</h2>\n                ";return d}function C(a,e){var c="";c+="\n                    <h2>"+n(f.t.call(a,gettext("Around The Web"),{hash:{},data:e}))+"</h2>\n                ";return c}this.compilerInfo=
[2,">= 1.0.0-rc.3"];var f=f||g.helpers,i=i||g.partials,a=a||{},g="",o,j=this,q="function",n=this.escapeExpression;if((o=f.partial.call(k,"discoveryCollection",{hash:{},inverse:j.noop,fn:j.program(1,function(a,e){var c="",d;c+="\n    ";if((d=f.each.call(a,a.collection,{hash:{},inverse:j.noop,fn:j.programWithDepth(b,e,a),data:e}))||d===0)c+=d;c+="\n";return c},a),data:a}))||o===0)g+=o;g+="\n\n";if((o=f.partial.call(k,"linkAttributes",{hash:{},inverse:j.noop,fn:j.program(18,function(a,e){var c="",d;
c+='\n    href="';(d=f.redirectUrl)?d=d.call(a,{hash:{},data:e}):(d=a.redirectUrl,d=typeof d===q?d.apply(a):d);c+=n(d)+'" ';if((d=f["if"].call(a,a.brand,{hash:{},inverse:j.noop,fn:j.program(19,s,e),data:e}))||d===0)c+=d;c+="\n";return c},a),data:a}))||o===0)g+=o;g+="\n\n";if((o=f.partial.call(k,"discoveryContentPreview",{hash:{},inverse:j.noop,fn:j.program(21,function(a,e){var D;var x;var v;var c="",d;c+="\n    <a ";if((d=j.invokePartial(i.linkAttributes,"linkAttributes",a,f,i,e))||d===0)c+=d;c+=
' class="top-comment" data-role="discovery-top-comment">\n        <img src="'+n((x=(v=(d=(d=a.preview,d==null||d===!1?d:d.author),d==null||d===!1?d:d.avatar),d=v,d==null||d===!1?d:d.cache),d=x,typeof d===q?d.apply(a):d))+'" alt="'+n(f.t.call(a,gettext("Avatar"),{hash:{},data:e}))+'" data-role="discovery-avatar">\n        <p><span class="user" data-role="discovery-top-comment-author">'+n((D=(d=(d=a.preview,d==null||d===!1?d:d.author),d==null||d===!1?d:d.name),d=D,typeof d===q?d.apply(a):d))+'</span> &#8212; <span data-role="discovery-top-comment-snippet" class="line-truncate" data-line-truncate="3">'+
n((d=(d=a.preview,d==null||d===!1?d:d.plaintext),typeof d===q?d.apply(a):d))+"</span></p>\n    </a>\n";return c},a),data:a}))||o===0)g+=o;g+="\n\n";if((o=f.partial.call(k,"discoveryPostCount",{hash:{},inverse:j.noop,fn:j.program(23,function(a,e){var c="",d;c+="\n    ";if((d=f["if"].call(a,a.posts===1,{hash:{},inverse:j.program(26,l,e),fn:j.program(24,t,e),data:e}))||d===0)c+=d;c+="\n";return c},a),data:a}))||o===0)g+=o;g+="\n\n";if((o=f.partial.call(k,"discoveryMain",{hash:{},inverse:j.noop,fn:j.programWithDepth(function(a,
e,c){var d="",b;d+='\n<div id="';(b=f.id)?b=b.call(a,{hash:{},data:e}):(b=a.id,b=typeof b===q?b.apply(a):b);d+=n(b)+'" class="discovery-main">\n    <div id="discovery-note" style="display:none;">\n        <div class="alert">\n        <a href="#" class="close" data-action="discovery-help-close" title="'+n(f.t.call(a,gettext("Close this box"),{hash:{},data:e}))+'">\u00d7</a>\n        '+n(f.t.call(a,gettext("Disqus helps you find new and interesting content, discussions and products. Some sponsors and ecommerce sites may pay us for these recommendations and links. %(learnMore)s or %(feedback)s."),
{hash:{learnMore:{partial:"learnMore",context:c,executePartial:!0},feedback:{partial:"feedback",context:c,executePartial:!0}},data:e}))+"\n        </div>\n    </div>\n\n    ";if((b=f.each.call(a,a.sections,{hash:{},inverse:j.noop,fn:j.programWithDepth(z,e,a),data:e}))||b===0)d+=b;d+="\n\n</div>\n";return d},a,k),data:a}))||o===0)g+=o;g+="\n\n";if((o=f.partial.call(k,"learnMore",{hash:{},inverse:j.noop,fn:j.program(36,function(a,e){var c="";c+='\n    <a href="http://help.disqus.com/customer/portal/articles/666278-introducing-promoted-discovery-and-f-a-q-"\n        target="_blank">'+
n(f.t.call(a,gettext("Learn more"),{hash:{},data:e}))+"</a>\n";return c},a),data:a}))||o===0)g+=o;g+="\n\n";if((o=f.partial.call(k,"feedback",{hash:{},inverse:j.noop,fn:j.program(38,function(a,e){var c="";c+='\n    <a href="https://www.surveymonkey.com/s/GHK872T" target="_blank">\n        '+n(f.t.call(a,gettext("give us feedback"),{hash:{},data:e}))+"</a>\n";return c},a),data:a}))||o===0)g+=o;g+="\n\n";if((o=f.partial.call(k,"forumName",{hash:{},inverse:j.noop,fn:j.program(40,function(a,e){var c=
"",d;c+="\n    <strong>";(d=f.name)?d=d.call(a,{hash:{},data:e}):(d=a.name,d=typeof d===q?d.apply(a):d);c+=n(d)+"</strong>\n";return c},a),data:a}))||o===0)g+=o;g+="\n";return g})})();
DISQUS.define("discovery.collections",function(){var l=DISQUS.JSON,g=_.strip,k=DISQUS.use("discovery.helpers"),f=DISQUS.use("discovery.models"),i=Backbone.Collection.extend({url:function(a){return DISQUS.api.getURL(a)},fetch:function(a){a=a||{};a.reset=!0;return Backbone.Collection.prototype.fetch.call(this,a)},parse:function(a){return a.response}}),a=function(a){var c=a.prototype;return a.extend({url:function(){return c.url.call(this,"discovery/listTopPost.json")},parse:function(a){for(var a=c.parse.call(this,
a),e=0,b=a.length;e<b;e++)a[e].plaintext=g(a[e].message);return a}})}(i),b=function(a){var c=a.prototype;return a.extend({initialize:function(){this.model=f[this.modelName];this.getBanditJSON=_.memoize(this.getBanditJSON)},parse:function(a){a=c.parse.call(this,a);if("bandit"in a)this.bandit=a.bandit,a=a.results;if(!_.isArray(a))return[];return a},getBanditJSON:function(){return l.stringify(this.bandit)}})}(i),h=function(a){var c=a.prototype;return a.extend({modelName:"RelatedThread",url:function(){return c.url.call(this,
"discovery/listRelated.json")},parse:function(a,e){return this.rejectInvalid(c.parse.call(this,a),e.sourceThread)},rejectInvalid:function(a,c){return _.filter(a,function(a){if(a.id==c.id||a.link==c.link)return this.reportInvalid(a,"Link or id of related thread points back to thread on this page (circular reference)"),!1;if(a.title.search(/^https?:\/\//)===0)return this.reportInvalid(a,"Title looks like a url (begins with http:// or https://)"),!1;return!0},this)},reportInvalid:function(a,c){var e=
k.log;e("An organic link failed validation:",a.title,a.link,"(id =",a.id+")");e("Reason:",c)}})}(b),c=function(a){var c=a.prototype;return a.extend({modelName:"Advertisement",url:function(){return c.url.call(this,"discovery/listPromoted.json")}})}(b),r=function(a){var c=a.prototype;return a.extend({modelName:"TempestAdvertisement",url:"//tempest.services.disqus.com/listPromoted",fetch:function(a){a=a||{};a.dataType="jsonp";a.data=a.data||{};if(_.has(a.data,"limit"))a.data.count=a.data.limit,delete a.data.limit;
_.has(a.data,"thread")&&delete a.data.thread;return c.fetch.call(this,a)}})}(c),a={PostCollection:a,RelatedThreadCollection:h,AdvertisementCollection:c,TempestAdvertisementCollection:r};if(DISQUS.testing)a.BaseCollection=i,a.BaseContentCollection=b;return a});
DISQUS.define("discovery",function(){var l=DISQUS.use("discovery.collections"),g=DISQUS.use("discovery.views"),k=DISQUS.use("discovery.helpers"),f=Backbone.Model.extend({defaults:{name:"promoted",inlineMeta:!0,contentPreviews:!1,promotedEnabled:!0,topPlacementEnabled:!1,redirectUrl:"//redirect.disqus.com/url",listRelatedLimit:null,listPromotedLimit:null,httpTimeout:1E4,sourceThread:null,sourceForum:null,useNewAdserver:!1,help:!1,display:!1,columnEveningEnabled:!0,numColumns:2,minPerColumn:1,maxPerColumn:4,
toleranceCoefficient:1.2,minWidthForColumnLayout:440,containerId:"discovery",topPlacementContainerId:"discovery-top",innerContainerName:"discovery-main",sectionNames:["col-organic","col-promoted"],collectionTagName:"ul",collectionClassName:"discovery-posts",consoleLoggingEnabled:DISQUS.debug,lineTruncationEnabled:!0,session:null,js:null,css:null},initialize:function(){var a=this;a.createDataReferences();a.configure();a.once("change:display",function(){a.onComplete()});_.bindAll(a,"getContentPreviews",
"validateData","showData");a.run()},configure:function(){var a=this;a.set("innerContainerId",a.get("innerContainerName")+"-"+a.cid);a.set("sectionIds",_.map(a.get("sectionNames"),function(b){return b+"-"+a.cid}));var b=a.get("session");a.get("topPlacementEnabled")&&b.isAnonymous()&&a.set("containerId",a.get("topPlacementContainerId"))},commonClickMetadata:function(){var a=this.get("sourceThread"),b=this.get("sourceForum"),a={redirectUrl:this.get("redirectUrl"),sourceThreadId:a.id,forumId:b.pk,forum:b.id,
majorVersion:this.majorVersion(),requestBin:this.get("requestBin")};if((b=this.get("session"))&&b.isRegistered())a.userId=b.user.id;return a},augmentModels:function(a){a.invoke("set",this.commonClickMetadata())},createDataReferences:function(){this.collections=[];this.threads=new l.RelatedThreadCollection;this.collections.push(this.threads);if(this.get("promotedEnabled"))this.ads=new (this.get("useNewAdserver")?l.TempestAdvertisementCollection:l.AdvertisementCollection),this.collections.push(this.ads);
_.invoke(this.collections,"on","reset",this.augmentModels,this)},run:function(){var a=_.bind(this.onComplete,this);this.getData().then(this.validateData).then(this.showData).otherwise(a)},generateFetchOptions:function(){var a=this.get("numColumns");return{timeout:this.get("httpTimeout"),data:{thread:this.get("sourceThread").id,limit:a/this.collections.length*this.get("maxPerColumn")},sourceThread:this.get("sourceThread")}},getDataOrganic:function(){var a=this.generateFetchOptions();a.humanFriendlyTimestamp=
!0;if(this.has("listRelatedLimit"))a.data.limit=this.get("listRelatedLimit");a=when(this.threads.fetch(a));this.get("contentPreviews")&&(a=a.then(this.getContentPreviews));return a},getDataPromoted:function(){var a=this,b=this.generateFetchOptions();if(a.has("listPromotedLimit"))b.data.limit=a.get("listPromotedLimit");var h=when(a.ads.fetch(b));return h.then(function(c){c=c.bin;if(!c)return h;if(a.has("requestBin"))return h;a.set("requestBin",c);_.invoke(a.collections,"invoke","set","requestBin",
c);return a.handleExperiment(c)})},getData:function(){var a=this.getDataOrganic();if(!this.get("promotedEnabled"))return a;var b=this.getDataPromoted();return when.join(a,b)},handleExperiment:function(a){if(a.substring(0,31)==="embed:discovery:tempest:taboola"){a=a.substring(31);if(this.experimentHandlers[a])this.experimentHandlers[a]();this.set("experimentVariant",a);return this.getDataPromoted()}},experimentHandlers:{taboola:function(){var a=this.ads;a.off();this.ads=new l.TaboolaAdvertisementCollection;
this.collections.splice(_.indexOf(this.collections,a),1,this.ads);this.ads.on("reset",this.augmentModels)}},getContentPreviews:function(){var a=this.threads.pluck("id"),b=this.collections.length,h=this.get("numColumns"),c=this.get("minPerColumn");if(a.length<h/b*c)return when.resolve();this.previews=new l.PostCollection;return(this.listTopPostRequest=when(this.previews.fetch({data:{thread:a},timeout:this.get("httpTimeout")}))).then(_.bind(this.attachPreviews,this))},attachPreviews:function(){var a=
this;a.previews.each(function(b){var h=b.get("thread");(h=a.threads.get(h.id||h))&&h.set("preview",b)})},validateCollections:function(){for(var a=this.collections,b=a.length,h=this.get("numColumns"),c=this.get("minPerColumn"),r,e;b>0;)if(e=h/a.length*c,r=a[--b],r.length<e)a.splice(b,1),b=a.length;b=a.length;if(b>0){h=h/b*this.get("maxPerColumn");for(c=0;c<b;c++)r=a[c],r.length>h&&r.reset(r.slice(0,h))}},validateData:function(){k.isMobile()&&this.ads&&this.ads.length>0&&this.ads.remove(this.ads.where({mobile:!1}));
this.validateCollections();if(this.collections.length===0)throw"Not enough data";},showData:function(){function a(a){_.extend(this,a);this.appContext=b.toJSON()}var b=this,h=document.getElementById(b.get("containerId"));if(!h)throw"No container on the DOM";h=b.mainView=new g.MainView(new a({el:h,model:b}));h.render();var c=b.get("sectionIds"),r=b.get("collectionTagName"),e=b.get("collectionClassName");b.views=_.map(b.collections,function(b,h){return new g.BaseCollectionView(new a({collection:b,el:$("#"+
c[h]+" "+r+"."+e)}))});b.views.length===2&&h.$el.find("#"+b.get("innerContainerId")).addClass("doublesection");_.invoke(b.views,"render");if(b.get("columnEveningEnabled")&&h.$el.width()>b.get("minWidthForColumnLayout"))(new g.TwoColumn({views:b.views,fudge:this.get("toleranceCoefficient")})).render();else{var f=_.min(_.pluck(b.collections,"length"));_.each(b.views,function(a){for(;a.collection.length>f;)a.collection.pop()})}b.set("display",!0)},onComplete:function(a){var b=k.log;if(this.onCompleteCalled)return b("Error: Final reporting function called more than once");
this.onCompleteCalled=!0;a&&b("It looks like there was a problem:",a);this.report()},report:function(){var a=k.log,b=this.snapshot(),h=DISQUS.juggler.client("juggler");if(!h)return void a("Cannot report app state, no client found");a("Sending analytics data about this Discovery impression:");a("init_discovery: ",b);h.emit("init_discovery",b);this.get("darkJester")&&DISQUS.juggler.client("jester",!0).emit("init_discovery",b)},majorVersion:function(){return this.get("promotedEnabled")?"midway":"metadata"},
snapshot:function(){var a=this.collections,b=this.threads,b={major_version:this.majorVersion(),internal_organic:b.length,external_organic:0,promoted:0,display:this.get("display"),placement:this.get("containerId")===this.get("topPlacementContainerId")?"top":"bottom"};if(this.has("requestBin"))b.bin=this.get("requestBin");if(this.get("promotedEnabled")){var h=this.ads;_.extend(b,{promoted:h.length,promoted_ids:DISQUS.JSON.stringify(h.pluck("advertisement_id"))})}a=_.extend.apply(_,[{}].concat(_.pluck(a,
"bandit")));if(!_.isEmpty(a))b.bandit=DISQUS.JSON.stringify(a);return b}}),i={};if(DISQUS.testing)i.DiscoveryApp=f;i.init=function(a){var b=_.object(_.map(["lineTruncationEnabled","consoleLoggingEnabled"],function(b){return b in a?[b,a[b]]:[b,f.prototype.defaults[b]]}));k.config(b);return new f(a)};return i});
DISQUS.define("discovery.views",function(){var l=DISQUS.use("discovery.helpers"),g=Backbone.View.extend({initialize:function(a){if(a&&a.appContext)this.appContext=a.appContext},getTemplateContext:function(){if(!this.appContext)return{};return{variant:this.appContext}},template:function(a,b){b=b||this.templateName;return DISQUS.renderBlock(b,a)}}),k=function(a){var b=a.prototype;return a.extend({events:{"click [data-redirect]":"handleClick"},handleClick:function(a){this.swapHref(a.currentTarget)},
swapHref:function(a){a.setAttribute("data-href",a.getAttribute("href"));a.setAttribute("href",a.getAttribute("data-redirect"));_.delay(function(){a.setAttribute("href",a.getAttribute("data-href"))},100)},templateName:"discoveryCollection",initialize:function(a){b.initialize.call(this,a);this.elementsSelector="li.discovery-post";this.$elements=this.$el.find(this.elementsSelector);a=this.collection;a.on("remove",this.remove,this);a.on("reset",this.render,this)},truncate:function(){this.$el.find(".line-truncate").each(function(a){a=
$(a);l.lineTruncate(a,{lines:a.attr("data-line-truncate"),ellipsis:!0})})},getTemplateContext:function(){var a=b.getTemplateContext.call(this);a.collection=this.collection.toJSON();var c=this.collection.at(0),h=c.has("id")?"organic-":"promoted-",f=c.idAttribute;_.each(a.collection,function(a){a.domIdSuffix=a[f];a.domIdSuffix=h+a.domIdSuffix});return a},render:function(){this.$el.html(this.template(this.getTemplateContext()));this.$elements=this.$el.find(this.elementsSelector);this.truncate();return this},
remove:function(a,c,b){if(arguments.length===0)return g.prototype.remove.call(this);var h=_.toArray(this.$elements),f=h.splice(b.index,1)[0];$(f).remove();this.$elements=$(h);return this}})}(g),f=function(a,b){this.modelIds=a||[];this.$elements=$(b||[])};_.extend(f.prototype,{height:function(){var a=this;a.heights=[];var b=$(a.$elements),e=b.first().offset().top,e=function(){var a=b.last().offset();return a.top+a.height}()-e,h=0;_.each(b,function(b){b=$(b).height();a.heights.push(b);h+=b});this.interstice=
(e-h)/(b.length-1);return e}});var i=function(){this.divideIntoColumns=function(){var a=this,b=a.subviews[0];a.left=new f;a.right=new f;var e=0;b.collection.each(function(h,f){var g=e++%2===0?"left":"right";a[g].modelIds.push(h.id);Array.prototype.push.call(a[g].$elements,b.$elements[f])})};this.removeOneFromColumn=function(a,b){var e=_.chain(a.modelIds).map(function(b,e){return[b,a.heights[e]]}).sortBy(function(a){return-1*a[1]}).find(function(a){return a[1]<=b}).value()[0],h=this.subviews[0].collection,
f=h.models,g=h.get(e),k=f.indexOf(g),e=[[],[]],m,s=f.length;for(m=0;m<s;m++)e[m%2].push(f[m]);f=e[k%2];f.splice(_.indexOf(f,g),1);f=[];g=(k+1)%2;for(m=0;m<s-1;m++)f.push(e[(m+g)%2].shift());h.reset(f)};this.balanceColumns=function(){var a=this.subviews[0],b=a.collection,e={};b.each(function(b,h){e[h]=a.$elements[h]});var h=l.balancedPartition(e),h=_.sortBy(h,"length"),f=h[0],g=b.models,k=Array(g.length);_.each(h[1],function(a,c){k[2*c]=g[c]});_.each(f,function(a,c){k[2*c+1]=g[c]});b.reset(g)};this.shortenColumn=
function(a,b){this.subviews[0].collection.length%2!==0&&a===this.left?this.removeOneFromColumn(a,this.fudge*b):this.balanceColumns()}},a=function(){this.divideIntoColumns=function(){var a=this.subviews,b=a[0],a=a[1];this.left=new f(b.collection.pluck(b.collection.model.prototype.idAttribute),b.$elements);this.right=new f(a.collection.pluck(a.collection.model.prototype.idAttribute),a.$elements)};this.shortenColumn=function(a,b){for(var e=a===this.left?this.right:this.left,h=b/e.$elements.length,f=
(a===this.left?this.subviews[0]:this.subviews[1]).collection,g=_.chain(a.modelIds).map(function(b,e){return[b,a.heights[e]]}).sortBy(function(a){return a[1]}).value(),k=[],m=0,i=b,i=h;g.length;){var l=g.pop(),v=l[0],l=l[1]+a.interstice;m+l>b&&(e=a);i=Math.abs(b-(m+l));i/=e.$elements.length;i>=h||(h=i,i=a.modelIds.indexOf(v),a.modelIds.splice(i,1),Array.prototype.splice.call(a.$elements,i,1),m+=l,k.push(v))}f.remove(k)}},b=function(b){this.fudge=b.fudge;this.subviews=b.views.slice(0,2);this.subviews.length===
1?i.call(this):a.call(this)};_.extend(b.prototype,{ascendingByHeight:function(){var a=this.left,b=this.right,a=[[a,a.height()],[b,b.height()]];return _.sortBy(a,function(a){return a[1]})},evenColumns:function(a){var b=this.ascendingByHeight(),e=b[0][0],h=b[0][1],f=b[1][0],b=b[1][1];if(h!==b){var h=b-h,g=this.fudge*h,b=_.find(f.heights,function(a){return a+f.interstice<g});if(!a&&b)return this.shortenColumn(f,h),this.divideIntoColumns(),this.evenColumns("do not recurse again");this.increaseMargins(e,
h)}},increaseMargins:function(a,b){var e=b/a.$elements.length;_.each(a.$elements,function(a){var a=$(a),b=parseInt(a.css("margin-bottom"),10)+e;a.css("margin-bottom",b+"px")});(a===this.left?this.right:this.left).$elements.css("clear",a===this.right?"left":"right")},render:function(){this.divideIntoColumns();this.evenColumns();return this}});var h=function(a){var b=a.prototype;return a.extend({templateName:"discoveryMain",events:{"click [data-action=discovery-help]":function(a){a.preventDefault();
this.model.set("help",!0)},"click [data-action=discovery-help-close]":function(a){a.preventDefault();this.model.set("help",!1)}},toggleHelp:function(a){this.$el.find("#discovery-note").toggle();a.trigger("resize")},initialize:function(a){b.initialize.call(this,a);this.model.on("change:display",this.show,this);this.model.on("change:help",this.toggleHelp,this);this.$el.css({position:"absolute",visibility:"hidden",display:"block"})},createSections:function(){var a=this.model,b=DISQUS.discovery.collections,
c=b.RelatedThreadCollection,h=b.AdvertisementCollection,f=a.get("sectionNames"),g=a.get("sectionIds");return _.map(a.collections,function(a,b){var e;a instanceof c?e="organic":a instanceof h&&(e="promoted");return{id:g[b],className:f[b],type:e}})},render:function(){var a=this.model,b=this.createSections();this.$el.html(this.template({id:a.get("innerContainerId"),sections:b,forum:a.get("sourceForum"),session:a.get("session").toJSON()}))},show:function(a){a.get("display")&&(this.$el.css({position:"static",
visibility:"visible"}),a.trigger("resize"))}})}(g);return{BaseCollectionView:k,TwoColumn:b,MainView:h}});
DISQUS.define("discovery.models",function(){var l=DISQUS.use("time"),g=function(a){var b=a.prototype;return a.extend({defaults:{redirectUrl:null,signedUrl:null,userId:null,sourceThreadId:null,forumId:null,forum:null,majorVersion:null,requestBin:null},redirectPayload:function(){var a={url:this.get("signedUrl"),imp:DISQUS.juggler.impId,forum_id:this.get("forumId"),forum:this.get("forum"),thread_id:this.get("sourceThreadId"),major_version:this.get("majorVersion")};if(this.has("requestBin"))a.bin=this.get("requestBin");
if(this.has("userId"))a.user_id=this.get("userId");if(this.collection&&this.collection.bandit)a.bandit=this.collection.getBanditJSON();return a},redirectUrl:function(){var a=this.get("redirectUrl"),b=this.redirectPayload();return DISQUS.serialize(a,b)},toJSON:function(){var a=b.toJSON.call(this);a.redirectUrl=this.redirectUrl();return a},toString:function(){return this.get("title")+" "+this.get("link")+" (id = "+this.id+")"}})}(Backbone.Model),k=function(a){var b=a.prototype;return a.extend({defaults:_.defaults({createdAgo:!1},
b.defaults),initialize:function(a,b){if(b&&b.humanFriendlyTimestamp){var f=l.assureTzOffset(this.get("createdAt")),f=moment(f,l.ISO_8601);this.set("createdAgo",f.fromNow())}},redirectPayload:function(){var a=b.redirectPayload.call(this);_.extend(a,{thread:this.id,zone:"internal_discovery"});return a},toJSON:function(){var a=b.toJSON.call(this);if(a.preview)a.preview=a.preview.toJSON();return a},toString:function(){return"organic link: "+b.toString.call(this)}})}(g),f=function(a){var b=a.prototype;
return a.extend({idAttribute:"body_id",defaults:_.defaults({brand:null,headline:null,text:null,url:null,advertisement_id:null,body_id:null,mobile:!0},b.defaults),get:function(a){if(a==="title")return this.attributes.headline;if(a==="link")return this.attributes.url;return b.get.call(this,a)},redirectPayload:function(){var a=b.redirectPayload.call(this);_.extend(a,{zone:"promoted_discovery",advertisement_id:this.get("advertisement_id")});if(this.has("body_id"))a.body_id=this.get("body_id");return a},
toJSON:function(){var a=b.toJSON.call(this);a.title=a.headline;a.link=a.url;return a},toString:function(){return"promoted link: "+b.toString.call(this)}})}(g),i=function(a){return a.extend({idAttribute:"advertisement_id",parse:function(a){a.signedUrl=a.signed_url;delete a.signed_url;return a}})}(f),k={RelatedThread:k,Advertisement:f,TempestAdvertisement:i};if(DISQUS.testing)k.BaseContentModel=g;return k});
DISQUS.define("discovery.helpers",function(l,g){var k=!1,f=!1,i=function(){};l.console&&(i=function(){if(f){var a=_.toArray(arguments);a.unshift("[Discovery]");l.console.log.apply?l.console.log.apply(l.console,a):l.console.log(a.join(" "))}});return{config:function(a){k=!!a.lineTruncationEnabled;f=!!a.consoleLoggingEnabled},isMobile:function(){return DISQUS.browser.mobile},log:i,allowLog:function(a){if(a===g)return f;f=!!a},allowLineTruncate:function(a){if(a===g)return k;k=!!a},lineTruncate:function(a,
b){function f(){return i.scrollHeight-i.offsetHeight>0.2*w}function c(){e.lastChild&&!_.contains(["...","\u2026"],e.lastChild.nodeValue)&&(p=e.appendChild(l.document.createTextNode(" "+u)),f()&&(e.removeChild(p),e.removeChild(e.lastChild),c()))}if(k){var g=DISQUS.logError||function(){};if(!a.closest("body").length)return void g("lineTruncate called on el not on DOM");if(a.text().length<1)return void g("lineTruncated called on empty el");if(_.any(a.children(),function(a){return a.nodeType!==3}))return void g("lineTruncate called on non-flat el");
var e=a[0],i=e;if(a.css("display")!=="block")for(;i.parentNode;)if(i=i.parentNode,$(i).css("display")==="block")break;var w=parseFloat(a.css("font-size"),10);if(f()){var b=b||{},g=b.lines||1,u=b.ellipsis,p,m=a.text();if(m.length){var s=a.width()/w,g=parseInt(s*g,10),m=m.split(/\s/),s=0;a.empty();for(var t=0,v=m.length;t<v;t++){s+=m[t].length+1;if(s>=g)break;e.appendChild(document.createTextNode(" "+m[t]))}if(f()){do p=e.removeChild(e.lastChild);while(f())}else{do p=e.appendChild(document.createTextNode(" "+
m[t++]));while(!f()&&t<v);e.removeChild(p)}u&&(_.isString(u)||(u="\u2026"),c())}}}},balancedPartition:function(a){var b=_.keys(a),f=Math.floor(_.reduce(a,function(a,b){return a+b},0)/2),c=b.length+1;f+=1;var g=Array(c),e,i;for(e=0;e<c;e++)g[e]=Array(f),g[e][0]={};for(i=1;i<f;i++)g[0][i]=!1;var k,l,p,m={};for(i=1;i<f;i++)for(e=1;e<c;e++){k=b[e-1];l=a[k];p=_.clone(g[e-1][i]);if(!p&&l<=i&&(p=_.clone(g[e-1][i-l])))p[k]=l,m=p;g[e][i]=p}return[m,_.omit(a,_.keys(m))]}}});