<?php
	function hellow_menu() {	
		$items = array();
		
	  $items['hellow'] = array(
		'page arguments' => array(1),
		'title' => t('hellow'),
		'page callback' => 'hellow_page',
		'type' => MENU_CALLBACK,
		'access arguments' => array('access content'),				
	  );

	  return $items;
	}
	
	function hellow_page($aar) {
		$output = "Hello World! через гет сюда передан аргумент: " . $aar;		
		
		return $output;
	}
