(function(){function C(a,c){var d=[],g;for(g in a){var h=c?c+"["+g+"]":g,k=a[g];d.push("object"==typeof k?C(k,h):encodeURIComponent(h)+"="+encodeURIComponent(k))}return d.join("&")}function O(a){if(!a||""==a)return"";for(;a&&-1<" \n\r\t".indexOf(a.charAt(0));)a=a.substring(1);for(;a&&-1<" \n\r\t".indexOf(a.charAt(a.length-1));)a=a.substring(0,a.length-1);return a}function D(a,c){function d(c,d){void 0!==a[c]||(a[c]=[]);var e=d.replace(RegExp("\\+","g"),"%20"),e=decodeURIComponent(e);a[c].push(e)}
for(var g=O(c).split("&"),h=0;h<g.length;h++)if(g[h]){var k=g[h].indexOf("=");0>k?d(g[h],"1"):d(g[h].substring(0,k),g[h].substring(k+1))}}function p(a){var c=window[E];if(void 0!==c&&"object"==typeof c)for(var d=0;d<c.length;d++)if(c[d]&&c[d][0]&&c[d][0]==a)return c[d][1]}function F(a){for(var c=("https:"==location.protocol?"https:":"http:")+P,d=[],g=0;g<a.length;g++)d.push("object"==typeof a[g][1]?C(a[g][1],a[g][0]):encodeURIComponent(a[g][0])+"="+encodeURIComponent(a[g][1]));return c+d.join("&")+
"&"+(Math.random()+Q)}function G(a){return(a=document.cookie.match(RegExp("(?:^|;\\s*)"+a+"=([^;]*)")))&&1 in a?decodeURIComponent(a[1]):null}function H(a,c,d,g){var h="";d&&(h=new Date,h.setTime(h.getTime()+6E4*d),h=";expires="+h.toGMTString());document.cookie=a+"="+encodeURIComponent(c)+h+";path="+(g||"/")}function I(){if(!u)try{u=new Date}catch(a){}return u}function R(){var a=I();return a&&"getTimezoneOffset"in a?a.getTimezoneOffset():666}function J(a,c){var d=document.getElementById("_zero_"+
a);if(d)for(var g=d.childNodes.length-1;0<=g;g--)d.removeChild(d.childNodes[g]);var h=document.createElement("a");h.href="http://zero.kz/?s="+a;h.target="_blank";var k=document.createElement("img");k.border="0px";k.width=88;k.height=31;k.alt="ZERO.KZ";k.src=c;k.onload=function(){d&&d.appendChild(h)&&h.appendChild(k)}}function w(a,c){"undefined"===typeof a&&(a="");var d,g=function(a,c){a=parseInt(a,10).toString(16);return c<a.length?a.slice(a.length-c):c>a.length?Array(1+(c-a.length)).join("0")+a:
a};this.php_js||(this.php_js={});this.php_js.uniqidSeed||(this.php_js.uniqidSeed=Math.floor(123456789*Math.random()));this.php_js.uniqidSeed++;d=a+g(parseInt((new Date).getTime()/1E3,10),8);d+=g(this.php_js.uniqidSeed,5);c&&(d+=(10*Math.random()).toFixed(8).toString());return d}function S(){var a=1;if((a=G(K))&&(14<a.length||13>a.length))a=void 0;a=a?a:"undefined"!=typeof L?L:w("",!1);1!=a&&H(K,a,525600,"/");return a}function T(){if(x)return!1;x=!0;var a=window.location.href;if(a!=v){if(!1!=v&&(0>=
a.indexOf("#")||a.match(/#.*(=|&|\?|\/|!)/)))y=a,q=v,u=!1,r=M(),r.push(["if",1]),J(z,F(r));v=a}x=!1;return!0}function M(){var a,c=[];c.push(["u",(a=p("id"),"number"==typeof a?a:0)]);c.push(["t",(a=p("type"),"number"==typeof a?a:1)]);c.push(["cc",S()]);var d=0,g=0,h=0,k=0,l=G(N);if(l&&(l=l.split("."),4==l.length&&(m=l[0],g=parseInt(l[1],10),d=parseInt(l[2],10),s=parseInt(l[3],10),m&&(14<m.length||13>m.length))))m=void 0;if((l=I())&&"getTime"in l)h=Math.round(l.getTime()/1E3),0<d&&(A=h-g,k=h-d);if(m){if(k>
U||0>k)B=m,m=w("",!1),s=0,g=h}else m=w("",!1),g=h;s++;H(N,m+"."+g+"."+h+"."+s,525600,"/");c.push(["s",m]);c.push(["sh",s]);0<=A&&c.push(["slt",A]);B&&c.push(["sls",B]);c.push(["d",(a=p("diff"),"number"==typeof a?a:0)]);if(a=window.screen)c.push(["wd","undefined"!=typeof a.width?a.width:0]),c.push(["hg","undefined"!=typeof a.height?a.height:0]),c.push(["cd",a.colorDepth?a.colorDepth:a.pixelDepth]);b=[];try{a=document;var f=a.documentElement,e=a.body,n=e&&e.clientWidth&&e.clientHeight;f&&f.clientWidth&&
f.clientHeight&&("CSS1Compat"===a.compatMode||!n)?b=[f.clientWidth,f.clientHeight]:n&&(b=[e.clientWidth,e.clientHeight])}catch(r){}a=b;2==a.length&&(c.push(["w","undefined"!=typeof a[0]?a[0]:0]),c.push(["h","undefined"!=typeof a[1]?a[1]:0]));c.push(["ln",(a=window.navigator,(a&&(a.language||a.browserLanguage)||"-").toLowerCase())]);c.push(["je",(a=window.navigator,a&&a.javaEnabled()?1:0)]);c.push(["cs",(a=document,a.characterSet||a.charset||"-")]);c.push(["ce",(a=window.navigator,a&&a.cookieEnabled?
1:0)]);a=[];f=window[E];if(void 0!==f&&"object"==typeof f)for(e=0;e<f.length;e++)f[e]&&(f[e][0]&&"add"==f[e][0])&&a.push(f[e]);for(f=0;f<a.length;f++)a[f]&&3<=a[f].length&&c.push([a[f][1],a[f][2]]);p("iframe")&&(y=q,q=null,c.push(["if",1]));window!=window.top&&c.push(["fi",1]);c.push(["du",y]);if(q){c.push(["rf",q]);a=q;e={url:a,protocol:"http",host:"",path:"",params:{},anchor:""};a&&(f=a.indexOf("://"),0<=f&&(e.protocol=a.substring(0,f),a=a.substring(f+3)),f=a.search("/|\\?|#"),0<=f?(e.host=a.substring(0,
f).toLowerCase(),"."==e.host.charAt(e.host.length-1)&&(e.host=e.host.substring(0,e.host.length-1)),a=a.substring(f),f=a.indexOf("#"),0<=f&&(e.anchor=a.substring(f+1),a=a.substring(0,f)),f=a.indexOf("?"),0<=f&&(D(e.params,a.substring(f+1)),a=a.substring(0,f)),e.anchor&&D(e.params,e.anchor),a&&"/"==a.charAt(0)&&(a=a.substring(1)),e.path=a):(e.host=a.toLowerCase(),"."==e.host.charAt(e.host.length-1)&&(e.host=e.host.substring(0,e.host.length-1))));urlComponents=e;a:{a=urlComponents;f=V;for(e=0;e<f.length;++e)if(n=
f[e].split(":"),-1<a.host.indexOf(n[0].toLowerCase())&&(d=a.params[n[1]],n[1]in a.params)){a=[a.host,"object"==typeof d?d&&0<d.length?d[0]:"":d,n[0]+":"+n[1]];break a}a=[]}3==a.length&&(c.push(["seh",a[0]]),c.push(["seq",a[1]]),c.push(["sem",a[2]]))}c.push(["tz",R()]);c.push(["dt",document.title.substring(0,255)]);return c}var L="2547a18d9ee5e5",Q=8,E="_zero_kz_",K="_zero_cc",N="_zero_ss",P="//c.zero.kz/z.png?",U=1800,m,B,A=0,s=0,y=window.location.href,q=document.referrer,v=!1,x=!1,V="images.google:q google:q yandex:text go.mail.ru:q bing:q daum:q eniro:search_word naver:query pchome:q yahoo:p yahoo:q msn:q aol:query aol:q lycos:q lycos:query ask:q netscape:query cnn:query about:terms mamma:q voila:rdata virgilio:qs live:q baidu:wd alice:qs najdi:q seznam:q rakuten:qt biglobe:q goo.ne:MT wp:szukaj onet:qt yam:k kvasir:q ozu:q terra:query rambler:query conduit:q babylon:q search-results:q avg:q comcast:q incredimail:q startsiden:q search.centrum.cz:q 360.cn:q".split(" "),
u,r=[],z=p("id");if(z){r=M();J(z,F(r));var t=p("url_watcher");(t="number"==typeof t?t:0)&&setInterval(T,100<t?t:100)}})();
